### ISSUE TITLE
Species seq file must be contained in any subdirectory

### ISSUE THREAD

**Issue by DavCP** [tmakwtnb/OrthoPhy#1]
After installing all the Python packages, I encountered the following error when trying to run OrthoPhy.py.

```
File "OrthoPhy.py", line 570, in <module>
    retry=retry)
  File "OrthoPhy.py", line 174, in __init__
    self.dirtype                 = self.validate_input()
  File "OrthoPhy.py", line 297, in validate_input
```

Any idea why this might happen?? The seq files are already inside a subdirectory

**Comment by tmakwtnb** [comment]
Thank you for contacting us.
I'm afraid for the inconvenience caused by the lack of documentation
regarding OrthoPhy (I will mentanance document in the future).
validate_input is a method that OrthoPhy checks the integrity of
parameters or options, and returns an error if an invalid value is inputted.
If you send us the command line, we may be able to provide a more
detailed response.
I am replying from out of town and apologize for the shortness of my
message.

**Comment by rbelmontelopes** [comment]
Hello, 

First off all, thanks for this nice pipeline, I am hopping it will help to solve my problem in estimating a species tree from the genome results (as the results I got with orthofinder on this case with very distant species are far from the topology expected).

I faced the same error described by DaVCP when running with `python3 OrthoPhy.py --indir indir_path --out out_path`

Changing OrthoPhy.py line 295 from `if direct_files:` to ` if not direct_files` solved the error.

Still, in  my computer (Ubuntu 22.04, system info in the end of the message), the analysis starts, and go through at least part of the step 1 (it generate the fasta files from the genbank files), but after that, when it seems to be moving to stage 2, instead of creating the db.fasta and doing the other calculations, it removes all files from the folder 01_fasta and generate an empty db.faa, with all the processing stooping at this point, with the processes entering sleep mode. Other strange thing is that If I start the process directly from the bash terminal, it start only one multiprocessing thread, but if I start it through IDLE it start several processes.

This is the log until this part, every time I have to kill the process, so it generates a keyboard interrupt message that I leaved out of the code below.

`/mnt/hd/OrthoPhy/OrthoPhy.py:40: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import StrictVersion
Ortholog-Finder2 analysis log (version 1.0)
/mnt/hd/OrthoPhy/OrthoPhy.py --indir /mnt/hd/OrthoPhy/gbk_files --out /mnt/hd/OrthoPhy/test
Start             : 2024-03-27T13:19:26
Input directory   : /mnt/hd/OrthoPhy/gbk_files
Output directory  : /mnt/hd/OrthoPhy/test
HGT Prediction    : OFF
Inflation         : 1.2 1.4 1.6 1.8 2.0
Coverage          : 50.0%
Minimum otu       : 4
Minimum group     : 2
Concatenated tree : ON (minimum species ortholog share rate among species: 50.0%)
Number of threads : 20

***** Extract gene sequences *****
***** Homology search *****
***** Inflation: 1.2 *****
***** Clustering *****`

As far as I was able to check, I have all the dependencies (the ones I was able to find) installed and available directly in the prompt, including Dimob.pl, and Dimob run in all the .gbk files. Any clue of what I should be missing?


An additional error that occured to me,  if I run OrthoPhy with `python3 /mnt/hd/OrthoPhy/OrthoPhy.py --indir indir_path --out out_path --hgt` I got the following error:

`Traceback (most recent call last):
  File "/mnt/hd/OrthoPhy/OrthoPhy.py", line 562, in <module>
    ortholog_finder = OrthologFinder(indir=indir, outdir=outdir, cpu=cpu,
  File "/mnt/hd/OrthoPhy/OrthoPhy.py", line 175, in __init__
    self.dirtype                 = self.validate_input()
  File "/mnt/hd/OrthoPhy/OrthoPhy.py", line 307, in validate_input
    raise ValueError(
ValueError: /mnt/hd/black_yeasts/datation/nucleotide/Peltula_sp.cds_from_genomic.fa is not a complete genome genbank file`

This error happens with .gbk files downloaded directly from NCBI (no modifications) and also with .gbk generated by Funannotate (removing one kind of file or the other does not solve the error).

Thanks for your time,

Best regards,

Ricardo

#system
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

#### python
Package                       Version
----------------------------- ----------------
abgdpy                        0.2.1
aiohttp                       3.9.0
aiosignal                     1.3.1
alabaster                     0.7.13
anndata                       0.10.6
annoy                         1.17.3
antismash                     6.0.0
apturl                        0.5.2
argcomplete                   3.2.2
argh                          0.31.2
array_api_compat              1.5.1
async-timeout                 4.0.3
attrs                         23.1.0
Babel                         2.14.0
bcbio-gff                     0.7.0
beautifulsoup4                4.10.0
bio                           1.6.0
bioconvert                    1.1.1
biopython                     1.81
biosniff                      1.0.0
biothings-client              0.3.1
blinker                       1.4
Brlapi                        0.8.3
certifi                       2020.6.20
chardet                       4.0.0
chrome-gnome-shell            0.0.0
click                         8.1.7
cloudpickle                   3.0.0
colorama                      0.4.4
coloredlogs                   15.0.1
colorlog                      6.8.0
command-not-found             0.3
configobj                     5.0.8
contourpy                     1.0.7
cryptography                  3.4.8
cssselect2                    0.7.0
cupshelpers                   1.0
cutadapt                      3.5
cycler                        0.11.0
Cython                        3.0.6
dask                          2024.3.1
dask-expr                     1.0.4
dbus-python                   1.2.18
DeepLoc2                      1.0.0
deepTools                     3.5.4.post1
deeptoolsintervals            0.1.9
defer                         1.0.6
diamond                       4.0.515
dill                          0.3.8
distro                        1.7.0
distro-info                   1.1+ubuntu0.2
dnaio                         0.7.1
dnspython                     2.1.0
docopt                        0.6.2
docutils                      0.20.1
easydev                       0.12.1
et-xmlfile                    1.1.0
ete3                          3.1.1
exceptiongroup                1.2.0
fair-esm                      2.0.0
fastqsplitter                 1.2.0
filelock                      3.13.1
flatbuffers                   23.5.26
fonttools                     4.39.4
frozenlist                    1.4.0
fsspec                        2023.10.0
future                        0.18.3
gffutils                      0.12
goatools                      1.3.11
gprofiler-official            1.0.0
graphviz                      0.20.1
h5py                          3.10.0
helperlibs                    0.2.1
html5lib                      1.1
httplib2                      0.20.2
huggingface-hub               0.19.4
humanfriendly                 10.0
idna                          3.3
imagesize                     1.4.1
imap                          1.0.0
importlib_metadata            7.1.0
iniconfig                     1.1.1
isal                          1.2.0
iso8601                       2.1.0
jeepney                       0.7.1
Jinja2                        3.1.2
joblib                        1.2.0
jsonschema                    4.17.3
kcalign                       1.0.2
keyring                       23.5.0
kiwisolver                    1.4.4
language-selector             0.1
launchpadlib                  1.10.16
lazr.restfulclient            0.14.4
lazr.uri                      1.0.6
lib-pod5                      0.3.2
lightning-utilities           0.10.0
llvmlite                      0.42.0
lml                           0.1.0
locket                        1.0.0
louis                         3.20.0
lxml                          4.9.2
macaroonbakery                1.3.1
MACS2                         2.2.7.1
mappy                         2.26
markdown-it-py                3.0.0
markup                        0.2
MarkupSafe                    2.1.3
matplotlib                    3.7.1
mdurl                         0.1.2
mitos                         2.1.3
more-itertools                8.10.0
mpmath                        1.3.0
multidict                     6.0.4
multiprocess                  0.70.16
mygene                        3.2.2
natsort                       8.4.0
netifaces                     0.11.0
networkx                      3.2.1
numba                         0.59.1
numpy                         1.24.3
numpydoc                      1.6.0
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.18.1
nvidia-nvjitlink-cu12         12.3.101
nvidia-nvtx-cu12              12.1.105
oauthlib                      3.2.0
olefile                       0.46
onnxruntime                   1.16.3
openpyxl                      3.0.10
packaging                     23.1
pandas                        2.0.2
Paralleltask                  0.2.2
partd                         1.4.1
pathlib                       1.0.1
patsy                         0.5.4
pexpect                       4.8.0
PhyloSuite                    1.2.2
Pillow                        9.0.1
pip                           22.0.2
platformdirs                  4.0.0
plotly                        5.18.0
pluggy                        0.13.0
pod5                          0.3.2
polars                        0.19.19
pooch                         1.8.0
protobuf                      3.12.4
psutil                        5.9.5
ptp                           1.1
ptyprocess                    0.7.0
py                            1.10.0
py2bit                        0.3.0
pyarrow                       14.0.1
pyBigWig                      0.3.22
pybktree                      1.1
pycairo                       1.20.1
pycups                        2.0.1
pydot                         2.0.0
pyexcel                       0.7.0
pyexcel-ezodf                 0.3.4
pyexcel-io                    0.6.6
pyexcel-ods3                  0.6.1
pyexcel-xls                   0.7.0
pyexcel-xlsx                  0.6.0
pyfaidx                       0.8.1.1
Pygments                      2.17.2
PyGObject                     3.42.1
PyJWT                         2.3.0
pymacaroons                   0.13.0
PyNaCl                        1.5.0
pynndescent                   0.5.11
pyparsing                     3.1.2
PyQt5                         5.15.9
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.12.1
pyRFC3339                     1.1
pyrsistent                    0.19.3
pysam                         0.22.0
pyScss                        1.4.0
pysvg-py3                     0.2.2.post3
pytest                        6.2.5
python-apt                    2.4.0+ubuntu3
python-dateutil               2.8.2
python-debian                 0.1.43+ubuntu1.1
pytorch-lightning             2.1.2
pytz                          2022.1
pyxdg                         0.27
PyYAML                        5.4.1
quast                         5.2.0
regex                         2023.10.3
reportlab                     3.6.8
requests                      2.25.1
rich                          13.7.1
safetensors                   0.4.0
scanpy                        1.9.8
scikit-learn                  1.2.2
scipy                         1.10.1
scour                         0.38.2
screen-resolution-extra       0.0.0
seaborn                       0.13.2
SecretStorage                 3.3.1
sentencepiece                 0.1.99
session-info                  1.0.0
setuptools                    59.6.0
simplejson                    3.17.6
six                           1.16.0
snowballstemmer               2.2.0
soupsieve                     2.3.1
Sphinx                        7.2.6
sphinxcontrib-applehelp       1.0.7
sphinxcontrib-devhelp         1.0.5
sphinxcontrib-htmlhelp        2.0.4
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.6
sphinxcontrib-serializinghtml 1.1.9
ssh-import-id                 5.11
statsmodels                   0.14.1
stdlib-list                   0.10.0
suds-py3                      1.4.5.0
svglib                        1.5.1
sympy                         1.12
systemd-python                234
tabulate                      0.9.0
tenacity                      8.2.3
texttable                     1.7.0
threadpoolctl                 3.1.0
tinycss2                      1.2.1
tokenizers                    0.15.0
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.1
torch                         2.1.1
torchmetrics                  1.2.0
tqdm                          4.66.1
transformers                  4.35.2
triton                        2.1.0
typing_extensions             4.8.0
tzdata                        2023.3
ubuntu-drivers-common         0.0.0
ubuntu-pro-client             8001
ufw                           0.36.1
umap-learn                    0.5.5
umi-tools                     1.1.4
unattended-upgrades           0.1
urllib3                       1.26.5
vboxapi                       1.0
vbz-h5py-plugin               1.0.1
wadllib                       1.3.6
webencodings                  0.5.1
wheel                         0.37.1
xdg                           5
xkit                          0.0.0
xlrd                          2.0.1
XlsxWriter                    3.2.0
xlwt                          1.3.0
xopen                         1.2.1
yarl                          1.9.3
zipp                          1.0.0

####
